### ISSUE TITLE
https connection not working

### ISSUE THREAD

**Issue by ritesh-probeatweaver** [ibm-watson-iot/custom-cards#1]
Hello,

I am trying build the custom cards for ibmiot platform however it's not working
When I try to access the node js server (by giving the IP address of the machine on which I am running the code), I get message in  the browser that the connection is not private.
It also says 'This server could not prove that it is 10.90.92.23; its security certificate is from'
The certificate also appears expired.
Please see the attached png image.
![https_error](https://cloud.githubusercontent.com/assets/27142091/24837597/3e4108e0-1d55-11e7-8525-32953c8c9309.PNG)
 When i give the the host address "https://10.90.92.23:6001" in 'ADD CUSTOM CARD SERVER' in bluemix, it never retives the certificate.

I using windows7 machine (64 bit) and during npm install i get following warnings:
![capture](https://cloud.githubusercontent.com/assets/27142091/24837538/033a0374-1d54-11e7-9758-39e60eff0fc2.PNG)

Please help to resolve this.

Best Regards,
Ritesh

**Comment by bryancboyd** [comment]
There is now a script available in the repo to generate a new self-signed certificate for the sample node.js server: https://github.com/ibm-watson-iot/custom-cards/blob/master/createSelfSignedCertificate.sh

Because the certificate is self-signed, you will still encounter the screenshot above; however, you can select the "proceed to website" option (exact language will vary by browser) and interact with the locally-hosted custom card configuration.
